### ISSUE TITLE
Wio Node fails to connect to private server

### ISSUE THREAD

**Issue by abelamtech** [Seeed-Studio/Wio_Link#60]
I configured a private server following the guidelines in the wiki and I was able to configure a new user, set it up in the Android app and login. However, during the configuration of a new Wio device it appears to fail while the Wio node is contacting the server through port 8000. I can see this error log in the server:

[I 180517 14:32:44 server:432] xchange device server accepted conns: 1
[E 180517 14:32:44 concurrent:139] Future exception was never retrieved: Traceback (most recent call last):
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 325, in start_serving
        ret = yield self.wait_hello()
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "server.py", line 103, in wait_hello
        io_loop=ioloop.IOLoop.current())
    TypeError: with_timeout() got an unexpected keyword argument 'io_loop'
[I 180517 14:32:44 server:429] ota device server accepted conns: 1
[E 180517 14:32:44 concurrent:139] Future exception was never retrieved: Traceback (most recent call last):
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 325, in start_serving
        ret = yield self.wait_hello()
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/marrero/AMTech/workspace/Wio_Link/env/local/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "server.py", line 103, in wait_hello
        io_loop=ioloop.IOLoop.current())
    TypeError: with_timeout() got an unexpected keyword argument 'io_loop'

Am I doing something wrong? Any ideas?

**Comment by abelamtech** [comment]
I solved the issue by downgrading tornado to the last v4.x.x (v4.5.3 at the time of this post). The signature for the method gen.with_timeout changed in v5 and it is incompatible with the code of the Wio Server.
